name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "${{ vars.DOCKER_BUILDER }}"
          install: true

      - name: Extract tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: "${{ vars.DOCKER_USER }}/${{ github.event.repository.name }}:${{ steps.get_tag.outputs.TAG }}-r1"
          platforms: linux/amd64
          provenance: mode=max
          sbom: true
          push: true
