name: Run tests and lint

on: [workflow_dispatch, workflow_call, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install prettier
        run: |
          mv package.json package.json.bak
          npm install prettier --no-save
          mv package.json.bak package.json
    
      - name: Run prettier
        run: npm run format

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '20.x' ]

    steps:
    - name: Install Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test

